// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/fissy/dialer/enrichedcall/historyquery/proto/history_result.proto

package com.fissy.dialer.enrichedcall.historyquery.proto;

public final class HistoryResultOuterClass {

    private HistoryResultOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
