// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/fissy/dialer/glidephotomanager/photo_info.proto

package com.fissy.dialer.glidephotomanager;

public final class PhotoInfoOuterClass {

    private PhotoInfoOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
