// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/fissy/dialer/logging/contact_source.proto

package com.fissy.dialer.logging;

public interface ContactSourceOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.fissy.dialer.logging.ContactSource)
        com.google.protobuf.MessageLiteOrBuilder {
}
