// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/fissy/dialer/logging/contact_lookup_result.proto

package com.fissy.dialer.logging;

public final class ContactLookupResultOuterClass {
    static {
    }

    private ContactLookupResultOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
