// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/fissy/dialer/logging/contact_lookup_result.proto

package com.fissy.dialer.logging;

public interface ContactLookupResultOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.fissy.dialer.logging.ContactLookupResult)
        com.google.protobuf.MessageLiteOrBuilder {
}
