// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/android/dialer/logging/dialer_impression.proto

package com.fissy.dialer.logging;

public interface DialerImpressionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fissy.dialer.logging.DialerImpression)
    com.google.protobuf.MessageLiteOrBuilder {
}
