// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/android/dialer/logging/people_api_lookup_error.proto

package com.fissy.dialer.logging;

public interface PeopleApiLookupErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fissy.dialer.logging.PeopleApiLookupError)
    com.google.protobuf.MessageLiteOrBuilder {
}
