// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/fissy/dialer/logging/screen_event.proto

package com.fissy.dialer.logging;

public interface ScreenEventOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.fissy.dialer.logging.ScreenEvent)
        com.google.protobuf.MessageLiteOrBuilder {
}
