// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/android/dialer/callintent/call_specific_app_data.proto

package com.fissy.dialer.callintent;

/**
 * <pre>
 * Miscellaneous data that's included in a new outgoing call initiated by
 * Dialer. The system will pass this data to the InCallUi which can use it
 * for logging or for something else.
 * Next tag: 15
 * </pre>
 *
 * Protobuf type {@code com.fissy.dialer.callintent.CallSpecificAppData}
 */
public  final class CallSpecificAppData extends
    com.google.protobuf.GeneratedMessageLite<
        CallSpecificAppData, CallSpecificAppData.Builder> implements
    // @@protoc_insertion_point(message_implements:com.fissy.dialer.callintent.CallSpecificAppData)
    CallSpecificAppDataOrBuilder {
  private CallSpecificAppData() {
    callInitiationType_ = 0;
    positionOfSelectedSearchResult_ = 0;
    charactersInSearchString_ = 0;
    speedDialContactType_ = emptyIntList();
    speedDialContactPosition_ = 0;
    timeSinceAppLaunch_ = 0L;
    timeSinceFirstClick_ = 0L;
    uiActionsSinceAppLaunch_ = emptyIntList();
    uiActionTimestampsSinceAppLaunch_ = emptyLongList();
    startingTabIndex_ = 0;
    lightbringerButtonAppearInExpandedCallLogItemCount_ = 0;
    lightbringerButtonAppearInCollapsedCallLogItemCount_ = 0;
    lightbringerButtonAppearInSearchCount_ = 0;
    allowAssistedDialing_ = false;
  }
  private int bitField0_;
  public static final int CALL_INITIATION_TYPE_FIELD_NUMBER = 1;
  private int callInitiationType_;
  /**
   * <code>optional .com.fissy.dialer.callintent.CallInitiationType.Type call_initiation_type = 1;</code>
   */
  public boolean hasCallInitiationType() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional .com.fissy.dialer.callintent.CallInitiationType.Type call_initiation_type = 1;</code>
   */
  public com.fissy.dialer.callintent.CallInitiationType.Type getCallInitiationType() {
    com.fissy.dialer.callintent.CallInitiationType.Type result = com.fissy.dialer.callintent.CallInitiationType.Type.forNumber(callInitiationType_);
    return result == null ? com.fissy.dialer.callintent.CallInitiationType.Type.UNKNOWN_INITIATION : result;
  }
  /**
   * <code>optional .com.fissy.dialer.callintent.CallInitiationType.Type call_initiation_type = 1;</code>
   */
  private void setCallInitiationType(com.fissy.dialer.callintent.CallInitiationType.Type value) {
    if (value == null) {
      throw new NullPointerException();
    }
    bitField0_ |= 0x00000001;
    callInitiationType_ = value.getNumber();
  }
  /**
   * <code>optional .com.fissy.dialer.callintent.CallInitiationType.Type call_initiation_type = 1;</code>
   */
  private void clearCallInitiationType() {
    bitField0_ = (bitField0_ & ~0x00000001);
    callInitiationType_ = 0;
  }

  public static final int POSITION_OF_SELECTED_SEARCH_RESULT_FIELD_NUMBER = 2;
  private int positionOfSelectedSearchResult_;
  /**
   * <code>optional int32 position_of_selected_search_result = 2;</code>
   */
  public boolean hasPositionOfSelectedSearchResult() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int32 position_of_selected_search_result = 2;</code>
   */
  public int getPositionOfSelectedSearchResult() {
    return positionOfSelectedSearchResult_;
  }
  /**
   * <code>optional int32 position_of_selected_search_result = 2;</code>
   */
  private void setPositionOfSelectedSearchResult(int value) {
    bitField0_ |= 0x00000002;
    positionOfSelectedSearchResult_ = value;
  }
  /**
   * <code>optional int32 position_of_selected_search_result = 2;</code>
   */
  private void clearPositionOfSelectedSearchResult() {
    bitField0_ = (bitField0_ & ~0x00000002);
    positionOfSelectedSearchResult_ = 0;
  }

  public static final int CHARACTERS_IN_SEARCH_STRING_FIELD_NUMBER = 3;
  private int charactersInSearchString_;
  /**
   * <code>optional int32 characters_in_search_string = 3;</code>
   */
  public boolean hasCharactersInSearchString() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional int32 characters_in_search_string = 3;</code>
   */
  public int getCharactersInSearchString() {
    return charactersInSearchString_;
  }
  /**
   * <code>optional int32 characters_in_search_string = 3;</code>
   */
  private void setCharactersInSearchString(int value) {
    bitField0_ |= 0x00000004;
    charactersInSearchString_ = value;
  }
  /**
   * <code>optional int32 characters_in_search_string = 3;</code>
   */
  private void clearCharactersInSearchString() {
    bitField0_ = (bitField0_ & ~0x00000004);
    charactersInSearchString_ = 0;
  }

  public static final int SPEED_DIAL_CONTACT_TYPE_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.IntList speedDialContactType_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, com.fissy.dialer.callintent.SpeedDialContactType.Type> speedDialContactType_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, com.fissy.dialer.callintent.SpeedDialContactType.Type>() {
            public com.fissy.dialer.callintent.SpeedDialContactType.Type convert(java.lang.Integer from) {
              com.fissy.dialer.callintent.SpeedDialContactType.Type result = com.fissy.dialer.callintent.SpeedDialContactType.Type.forNumber(from);
              return result == null ? com.fissy.dialer.callintent.SpeedDialContactType.Type.UNDEFINED : result;
            }
          };
  /**
   * <code>repeated .com.fissy.dialer.callintent.SpeedDialContactType.Type speed_dial_contact_type = 4;</code>
   */
  public java.util.List<com.fissy.dialer.callintent.SpeedDialContactType.Type> getSpeedDialContactTypeList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, com.fissy.dialer.callintent.SpeedDialContactType.Type>(speedDialContactType_, speedDialContactType_converter_);
  }
  /**
   * <code>repeated .com.fissy.dialer.callintent.SpeedDialContactType.Type speed_dial_contact_type = 4;</code>
   */
  public int getSpeedDialContactTypeCount() {
    return speedDialContactType_.size();
  }
  /**
   * <code>repeated .com.fissy.dialer.callintent.SpeedDialContactType.Type speed_dial_contact_type = 4;</code>
   */
  public com.fissy.dialer.callintent.SpeedDialContactType.Type getSpeedDialContactType(int index) {
    return speedDialContactType_converter_.convert(speedDialContactType_.getInt(index));
  }
  private void ensureSpeedDialContactTypeIsMutable() {
    if (!speedDialContactType_.isModifiable()) {
      speedDialContactType_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(speedDialContactType_);
    }
  }
  /**
   * <code>repeated .com.fissy.dialer.callintent.SpeedDialContactType.Type speed_dial_contact_type = 4;</code>
   */
  private void setSpeedDialContactType(
      int index, com.fissy.dialer.callintent.SpeedDialContactType.Type value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureSpeedDialContactTypeIsMutable();
    speedDialContactType_.setInt(index, value.getNumber());
  }
  /**
   * <code>repeated .com.fissy.dialer.callintent.SpeedDialContactType.Type speed_dial_contact_type = 4;</code>
   */
  private void addSpeedDialContactType(com.fissy.dialer.callintent.SpeedDialContactType.Type value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureSpeedDialContactTypeIsMutable();
    speedDialContactType_.addInt(value.getNumber());
  }
  /**
   * <code>repeated .com.fissy.dialer.callintent.SpeedDialContactType.Type speed_dial_contact_type = 4;</code>
   */
  private void addAllSpeedDialContactType(
      java.lang.Iterable<? extends com.fissy.dialer.callintent.SpeedDialContactType.Type> values) {
    ensureSpeedDialContactTypeIsMutable();
    for (com.fissy.dialer.callintent.SpeedDialContactType.Type value : values) {
      speedDialContactType_.addInt(value.getNumber());
    }
  }
  /**
   * <code>repeated .com.fissy.dialer.callintent.SpeedDialContactType.Type speed_dial_contact_type = 4;</code>
   */
  private void clearSpeedDialContactType() {
    speedDialContactType_ = emptyIntList();
  }

  public static final int SPEED_DIAL_CONTACT_POSITION_FIELD_NUMBER = 5;
  private int speedDialContactPosition_;
  /**
   * <code>optional int32 speed_dial_contact_position = 5;</code>
   */
  public boolean hasSpeedDialContactPosition() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional int32 speed_dial_contact_position = 5;</code>
   */
  public int getSpeedDialContactPosition() {
    return speedDialContactPosition_;
  }
  /**
   * <code>optional int32 speed_dial_contact_position = 5;</code>
   */
  private void setSpeedDialContactPosition(int value) {
    bitField0_ |= 0x00000008;
    speedDialContactPosition_ = value;
  }
  /**
   * <code>optional int32 speed_dial_contact_position = 5;</code>
   */
  private void clearSpeedDialContactPosition() {
    bitField0_ = (bitField0_ & ~0x00000008);
    speedDialContactPosition_ = 0;
  }

  public static final int TIME_SINCE_APP_LAUNCH_FIELD_NUMBER = 6;
  private long timeSinceAppLaunch_;
  /**
   * <code>optional int64 time_since_app_launch = 6;</code>
   */
  public boolean hasTimeSinceAppLaunch() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional int64 time_since_app_launch = 6;</code>
   */
  public long getTimeSinceAppLaunch() {
    return timeSinceAppLaunch_;
  }
  /**
   * <code>optional int64 time_since_app_launch = 6;</code>
   */
  private void setTimeSinceAppLaunch(long value) {
    bitField0_ |= 0x00000010;
    timeSinceAppLaunch_ = value;
  }
  /**
   * <code>optional int64 time_since_app_launch = 6;</code>
   */
  private void clearTimeSinceAppLaunch() {
    bitField0_ = (bitField0_ & ~0x00000010);
    timeSinceAppLaunch_ = 0L;
  }

  public static final int TIME_SINCE_FIRST_CLICK_FIELD_NUMBER = 7;
  private long timeSinceFirstClick_;
  /**
   * <code>optional int64 time_since_first_click = 7;</code>
   */
  public boolean hasTimeSinceFirstClick() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional int64 time_since_first_click = 7;</code>
   */
  public long getTimeSinceFirstClick() {
    return timeSinceFirstClick_;
  }
  /**
   * <code>optional int64 time_since_first_click = 7;</code>
   */
  private void setTimeSinceFirstClick(long value) {
    bitField0_ |= 0x00000020;
    timeSinceFirstClick_ = value;
  }
  /**
   * <code>optional int64 time_since_first_click = 7;</code>
   */
  private void clearTimeSinceFirstClick() {
    bitField0_ = (bitField0_ & ~0x00000020);
    timeSinceFirstClick_ = 0L;
  }

  public static final int UI_ACTIONS_SINCE_APP_LAUNCH_FIELD_NUMBER = 8;
  private com.google.protobuf.Internal.IntList uiActionsSinceAppLaunch_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, com.fissy.dialer.logging.UiAction.Type> uiActionsSinceAppLaunch_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, com.fissy.dialer.logging.UiAction.Type>() {
            public com.fissy.dialer.logging.UiAction.Type convert(java.lang.Integer from) {
              com.fissy.dialer.logging.UiAction.Type result = com.fissy.dialer.logging.UiAction.Type.forNumber(from);
              return result == null ? com.fissy.dialer.logging.UiAction.Type.UNKNOWN : result;
            }
          };
  /**
   * <pre>
   * The following two list should be of the same length
   * (adding another message is not allowed here)
   * </pre>
   *
   * <code>repeated .com.fissy.dialer.logging.UiAction.Type ui_actions_since_app_launch = 8;</code>
   */
  public java.util.List<com.fissy.dialer.logging.UiAction.Type> getUiActionsSinceAppLaunchList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, com.fissy.dialer.logging.UiAction.Type>(uiActionsSinceAppLaunch_, uiActionsSinceAppLaunch_converter_);
  }
  /**
   * <pre>
   * The following two list should be of the same length
   * (adding another message is not allowed here)
   * </pre>
   *
   * <code>repeated .com.fissy.dialer.logging.UiAction.Type ui_actions_since_app_launch = 8;</code>
   */
  public int getUiActionsSinceAppLaunchCount() {
    return uiActionsSinceAppLaunch_.size();
  }
  /**
   * <pre>
   * The following two list should be of the same length
   * (adding another message is not allowed here)
   * </pre>
   *
   * <code>repeated .com.fissy.dialer.logging.UiAction.Type ui_actions_since_app_launch = 8;</code>
   */
  public com.fissy.dialer.logging.UiAction.Type getUiActionsSinceAppLaunch(int index) {
    return uiActionsSinceAppLaunch_converter_.convert(uiActionsSinceAppLaunch_.getInt(index));
  }
  private void ensureUiActionsSinceAppLaunchIsMutable() {
    if (!uiActionsSinceAppLaunch_.isModifiable()) {
      uiActionsSinceAppLaunch_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(uiActionsSinceAppLaunch_);
    }
  }
  /**
   * <pre>
   * The following two list should be of the same length
   * (adding another message is not allowed here)
   * </pre>
   *
   * <code>repeated .com.fissy.dialer.logging.UiAction.Type ui_actions_since_app_launch = 8;</code>
   */
  private void setUiActionsSinceAppLaunch(
      int index, com.fissy.dialer.logging.UiAction.Type value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureUiActionsSinceAppLaunchIsMutable();
    uiActionsSinceAppLaunch_.setInt(index, value.getNumber());
  }
  /**
   * <pre>
   * The following two list should be of the same length
   * (adding another message is not allowed here)
   * </pre>
   *
   * <code>repeated .com.fissy.dialer.logging.UiAction.Type ui_actions_since_app_launch = 8;</code>
   */
  private void addUiActionsSinceAppLaunch(com.fissy.dialer.logging.UiAction.Type value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureUiActionsSinceAppLaunchIsMutable();
    uiActionsSinceAppLaunch_.addInt(value.getNumber());
  }
  /**
   * <pre>
   * The following two list should be of the same length
   * (adding another message is not allowed here)
   * </pre>
   *
   * <code>repeated .com.fissy.dialer.logging.UiAction.Type ui_actions_since_app_launch = 8;</code>
   */
  private void addAllUiActionsSinceAppLaunch(
      java.lang.Iterable<? extends com.fissy.dialer.logging.UiAction.Type> values) {
    ensureUiActionsSinceAppLaunchIsMutable();
    for (com.fissy.dialer.logging.UiAction.Type value : values) {
      uiActionsSinceAppLaunch_.addInt(value.getNumber());
    }
  }
  /**
   * <pre>
   * The following two list should be of the same length
   * (adding another message is not allowed here)
   * </pre>
   *
   * <code>repeated .com.fissy.dialer.logging.UiAction.Type ui_actions_since_app_launch = 8;</code>
   */
  private void clearUiActionsSinceAppLaunch() {
    uiActionsSinceAppLaunch_ = emptyIntList();
  }

  public static final int UI_ACTION_TIMESTAMPS_SINCE_APP_LAUNCH_FIELD_NUMBER = 9;
  private com.google.protobuf.Internal.LongList uiActionTimestampsSinceAppLaunch_;
  /**
   * <code>repeated int64 ui_action_timestamps_since_app_launch = 9;</code>
   */
  public java.util.List<java.lang.Long>
      getUiActionTimestampsSinceAppLaunchList() {
    return uiActionTimestampsSinceAppLaunch_;
  }
  /**
   * <code>repeated int64 ui_action_timestamps_since_app_launch = 9;</code>
   */
  public int getUiActionTimestampsSinceAppLaunchCount() {
    return uiActionTimestampsSinceAppLaunch_.size();
  }
  /**
   * <code>repeated int64 ui_action_timestamps_since_app_launch = 9;</code>
   */
  public long getUiActionTimestampsSinceAppLaunch(int index) {
    return uiActionTimestampsSinceAppLaunch_.getLong(index);
  }
  private void ensureUiActionTimestampsSinceAppLaunchIsMutable() {
    if (!uiActionTimestampsSinceAppLaunch_.isModifiable()) {
      uiActionTimestampsSinceAppLaunch_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(uiActionTimestampsSinceAppLaunch_);
     }
  }
  /**
   * <code>repeated int64 ui_action_timestamps_since_app_launch = 9;</code>
   */
  private void setUiActionTimestampsSinceAppLaunch(
      int index, long value) {
    ensureUiActionTimestampsSinceAppLaunchIsMutable();
    uiActionTimestampsSinceAppLaunch_.setLong(index, value);
  }
  /**
   * <code>repeated int64 ui_action_timestamps_since_app_launch = 9;</code>
   */
  private void addUiActionTimestampsSinceAppLaunch(long value) {
    ensureUiActionTimestampsSinceAppLaunchIsMutable();
    uiActionTimestampsSinceAppLaunch_.addLong(value);
  }
  /**
   * <code>repeated int64 ui_action_timestamps_since_app_launch = 9;</code>
   */
  private void addAllUiActionTimestampsSinceAppLaunch(
      java.lang.Iterable<? extends java.lang.Long> values) {
    ensureUiActionTimestampsSinceAppLaunchIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, uiActionTimestampsSinceAppLaunch_);
  }
  /**
   * <code>repeated int64 ui_action_timestamps_since_app_launch = 9;</code>
   */
  private void clearUiActionTimestampsSinceAppLaunch() {
    uiActionTimestampsSinceAppLaunch_ = emptyLongList();
  }

  public static final int STARTING_TAB_INDEX_FIELD_NUMBER = 10;
  private int startingTabIndex_;
  /**
   * <code>optional int32 starting_tab_index = 10;</code>
   */
  public boolean hasStartingTabIndex() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional int32 starting_tab_index = 10;</code>
   */
  public int getStartingTabIndex() {
    return startingTabIndex_;
  }
  /**
   * <code>optional int32 starting_tab_index = 10;</code>
   */
  private void setStartingTabIndex(int value) {
    bitField0_ |= 0x00000040;
    startingTabIndex_ = value;
  }
  /**
   * <code>optional int32 starting_tab_index = 10;</code>
   */
  private void clearStartingTabIndex() {
    bitField0_ = (bitField0_ & ~0x00000040);
    startingTabIndex_ = 0;
  }

  public static final int LIGHTBRINGER_BUTTON_APPEAR_IN_EXPANDED_CALL_LOG_ITEM_COUNT_FIELD_NUMBER = 11;
  private int lightbringerButtonAppearInExpandedCallLogItemCount_;
  /**
   * <pre>
   * For recording the appearance of video call button
   * </pre>
   *
   * <code>optional int32 lightbringer_button_appear_in_expanded_call_log_item_count = 11;</code>
   */
  public boolean hasLightbringerButtonAppearInExpandedCallLogItemCount() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <pre>
   * For recording the appearance of video call button
   * </pre>
   *
   * <code>optional int32 lightbringer_button_appear_in_expanded_call_log_item_count = 11;</code>
   */
  public int getLightbringerButtonAppearInExpandedCallLogItemCount() {
    return lightbringerButtonAppearInExpandedCallLogItemCount_;
  }
  /**
   * <pre>
   * For recording the appearance of video call button
   * </pre>
   *
   * <code>optional int32 lightbringer_button_appear_in_expanded_call_log_item_count = 11;</code>
   */
  private void setLightbringerButtonAppearInExpandedCallLogItemCount(int value) {
    bitField0_ |= 0x00000080;
    lightbringerButtonAppearInExpandedCallLogItemCount_ = value;
  }
  /**
   * <pre>
   * For recording the appearance of video call button
   * </pre>
   *
   * <code>optional int32 lightbringer_button_appear_in_expanded_call_log_item_count = 11;</code>
   */
  private void clearLightbringerButtonAppearInExpandedCallLogItemCount() {
    bitField0_ = (bitField0_ & ~0x00000080);
    lightbringerButtonAppearInExpandedCallLogItemCount_ = 0;
  }

  public static final int LIGHTBRINGER_BUTTON_APPEAR_IN_COLLAPSED_CALL_LOG_ITEM_COUNT_FIELD_NUMBER = 12;
  private int lightbringerButtonAppearInCollapsedCallLogItemCount_;
  /**
   * <code>optional int32 lightbringer_button_appear_in_collapsed_call_log_item_count = 12;</code>
   */
  public boolean hasLightbringerButtonAppearInCollapsedCallLogItemCount() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional int32 lightbringer_button_appear_in_collapsed_call_log_item_count = 12;</code>
   */
  public int getLightbringerButtonAppearInCollapsedCallLogItemCount() {
    return lightbringerButtonAppearInCollapsedCallLogItemCount_;
  }
  /**
   * <code>optional int32 lightbringer_button_appear_in_collapsed_call_log_item_count = 12;</code>
   */
  private void setLightbringerButtonAppearInCollapsedCallLogItemCount(int value) {
    bitField0_ |= 0x00000100;
    lightbringerButtonAppearInCollapsedCallLogItemCount_ = value;
  }
  /**
   * <code>optional int32 lightbringer_button_appear_in_collapsed_call_log_item_count = 12;</code>
   */
  private void clearLightbringerButtonAppearInCollapsedCallLogItemCount() {
    bitField0_ = (bitField0_ & ~0x00000100);
    lightbringerButtonAppearInCollapsedCallLogItemCount_ = 0;
  }

  public static final int LIGHTBRINGER_BUTTON_APPEAR_IN_SEARCH_COUNT_FIELD_NUMBER = 13;
  private int lightbringerButtonAppearInSearchCount_;
  /**
   * <code>optional int32 lightbringer_button_appear_in_search_count = 13;</code>
   */
  public boolean hasLightbringerButtonAppearInSearchCount() {
    return ((bitField0_ & 0x00000200) == 0x00000200);
  }
  /**
   * <code>optional int32 lightbringer_button_appear_in_search_count = 13;</code>
   */
  public int getLightbringerButtonAppearInSearchCount() {
    return lightbringerButtonAppearInSearchCount_;
  }
  /**
   * <code>optional int32 lightbringer_button_appear_in_search_count = 13;</code>
   */
  private void setLightbringerButtonAppearInSearchCount(int value) {
    bitField0_ |= 0x00000200;
    lightbringerButtonAppearInSearchCount_ = value;
  }
  /**
   * <code>optional int32 lightbringer_button_appear_in_search_count = 13;</code>
   */
  private void clearLightbringerButtonAppearInSearchCount() {
    bitField0_ = (bitField0_ & ~0x00000200);
    lightbringerButtonAppearInSearchCount_ = 0;
  }

  public static final int ALLOW_ASSISTED_DIALING_FIELD_NUMBER = 14;
  private boolean allowAssistedDialing_;
  /**
   * <pre>
   * Indicates that the call is open to modification from assisted dialing.
   * </pre>
   *
   * <code>optional bool allow_assisted_dialing = 14;</code>
   */
  public boolean hasAllowAssistedDialing() {
    return ((bitField0_ & 0x00000400) == 0x00000400);
  }
  /**
   * <pre>
   * Indicates that the call is open to modification from assisted dialing.
   * </pre>
   *
   * <code>optional bool allow_assisted_dialing = 14;</code>
   */
  public boolean getAllowAssistedDialing() {
    return allowAssistedDialing_;
  }
  /**
   * <pre>
   * Indicates that the call is open to modification from assisted dialing.
   * </pre>
   *
   * <code>optional bool allow_assisted_dialing = 14;</code>
   */
  private void setAllowAssistedDialing(boolean value) {
    bitField0_ |= 0x00000400;
    allowAssistedDialing_ = value;
  }
  /**
   * <pre>
   * Indicates that the call is open to modification from assisted dialing.
   * </pre>
   *
   * <code>optional bool allow_assisted_dialing = 14;</code>
   */
  private void clearAllowAssistedDialing() {
    bitField0_ = (bitField0_ & ~0x00000400);
    allowAssistedDialing_ = false;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeEnum(1, callInitiationType_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, positionOfSelectedSearchResult_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, charactersInSearchString_);
    }
    for (int i = 0; i < speedDialContactType_.size(); i++) {
      output.writeEnum(4, speedDialContactType_.getInt(i));
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt32(5, speedDialContactPosition_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeInt64(6, timeSinceAppLaunch_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeInt64(7, timeSinceFirstClick_);
    }
    for (int i = 0; i < uiActionsSinceAppLaunch_.size(); i++) {
      output.writeEnum(8, uiActionsSinceAppLaunch_.getInt(i));
    }
    for (int i = 0; i < uiActionTimestampsSinceAppLaunch_.size(); i++) {
      output.writeInt64(9, uiActionTimestampsSinceAppLaunch_.getLong(i));
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeInt32(10, startingTabIndex_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeInt32(11, lightbringerButtonAppearInExpandedCallLogItemCount_);
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeInt32(12, lightbringerButtonAppearInCollapsedCallLogItemCount_);
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      output.writeInt32(13, lightbringerButtonAppearInSearchCount_);
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      output.writeBool(14, allowAssistedDialing_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, callInitiationType_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, positionOfSelectedSearchResult_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, charactersInSearchString_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < speedDialContactType_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(speedDialContactType_.getInt(i));
      }
      size += dataSize;
      size += 1 * speedDialContactType_.size();
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, speedDialContactPosition_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, timeSinceAppLaunch_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, timeSinceFirstClick_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < uiActionsSinceAppLaunch_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(uiActionsSinceAppLaunch_.getInt(i));
      }
      size += dataSize;
      size += 1 * uiActionsSinceAppLaunch_.size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < uiActionTimestampsSinceAppLaunch_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(uiActionTimestampsSinceAppLaunch_.getLong(i));
      }
      size += dataSize;
      size += 1 * getUiActionTimestampsSinceAppLaunchList().size();
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, startingTabIndex_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, lightbringerButtonAppearInExpandedCallLogItemCount_);
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, lightbringerButtonAppearInCollapsedCallLogItemCount_);
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, lightbringerButtonAppearInSearchCount_);
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, allowAssistedDialing_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static com.fissy.dialer.callintent.CallSpecificAppData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.fissy.dialer.callintent.CallSpecificAppData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.fissy.dialer.callintent.CallSpecificAppData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.fissy.dialer.callintent.CallSpecificAppData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.fissy.dialer.callintent.CallSpecificAppData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.fissy.dialer.callintent.CallSpecificAppData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.fissy.dialer.callintent.CallSpecificAppData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.fissy.dialer.callintent.CallSpecificAppData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.fissy.dialer.callintent.CallSpecificAppData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.fissy.dialer.callintent.CallSpecificAppData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fissy.dialer.callintent.CallSpecificAppData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Miscellaneous data that's included in a new outgoing call initiated by
   * Dialer. The system will pass this data to the InCallUi which can use it
   * for logging or for something else.
   * Next tag: 15
   * </pre>
   *
   * Protobuf type {@code com.fissy.dialer.callintent.CallSpecificAppData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.fissy.dialer.callintent.CallSpecificAppData, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.fissy.dialer.callintent.CallSpecificAppData)
      com.fissy.dialer.callintent.CallSpecificAppDataOrBuilder {
    // Construct using com.fissy.dialer.callintent.CallSpecificAppData.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .com.fissy.dialer.callintent.CallInitiationType.Type call_initiation_type = 1;</code>
     */
    public boolean hasCallInitiationType() {
      return instance.hasCallInitiationType();
    }
    /**
     * <code>optional .com.fissy.dialer.callintent.CallInitiationType.Type call_initiation_type = 1;</code>
     */
    public com.fissy.dialer.callintent.CallInitiationType.Type getCallInitiationType() {
      return instance.getCallInitiationType();
    }
    /**
     * <code>optional .com.fissy.dialer.callintent.CallInitiationType.Type call_initiation_type = 1;</code>
     */
    public Builder setCallInitiationType(com.fissy.dialer.callintent.CallInitiationType.Type value) {
      copyOnWrite();
      instance.setCallInitiationType(value);
      return this;
    }
    /**
     * <code>optional .com.fissy.dialer.callintent.CallInitiationType.Type call_initiation_type = 1;</code>
     */
    public Builder clearCallInitiationType() {
      copyOnWrite();
      instance.clearCallInitiationType();
      return this;
    }

    /**
     * <code>optional int32 position_of_selected_search_result = 2;</code>
     */
    public boolean hasPositionOfSelectedSearchResult() {
      return instance.hasPositionOfSelectedSearchResult();
    }
    /**
     * <code>optional int32 position_of_selected_search_result = 2;</code>
     */
    public int getPositionOfSelectedSearchResult() {
      return instance.getPositionOfSelectedSearchResult();
    }
    /**
     * <code>optional int32 position_of_selected_search_result = 2;</code>
     */
    public Builder setPositionOfSelectedSearchResult(int value) {
      copyOnWrite();
      instance.setPositionOfSelectedSearchResult(value);
      return this;
    }
    /**
     * <code>optional int32 position_of_selected_search_result = 2;</code>
     */
    public Builder clearPositionOfSelectedSearchResult() {
      copyOnWrite();
      instance.clearPositionOfSelectedSearchResult();
      return this;
    }

    /**
     * <code>optional int32 characters_in_search_string = 3;</code>
     */
    public boolean hasCharactersInSearchString() {
      return instance.hasCharactersInSearchString();
    }
    /**
     * <code>optional int32 characters_in_search_string = 3;</code>
     */
    public int getCharactersInSearchString() {
      return instance.getCharactersInSearchString();
    }
    /**
     * <code>optional int32 characters_in_search_string = 3;</code>
     */
    public Builder setCharactersInSearchString(int value) {
      copyOnWrite();
      instance.setCharactersInSearchString(value);
      return this;
    }
    /**
     * <code>optional int32 characters_in_search_string = 3;</code>
     */
    public Builder clearCharactersInSearchString() {
      copyOnWrite();
      instance.clearCharactersInSearchString();
      return this;
    }

    /**
     * <code>repeated .com.fissy.dialer.callintent.SpeedDialContactType.Type speed_dial_contact_type = 4;</code>
     */
    public java.util.List<com.fissy.dialer.callintent.SpeedDialContactType.Type> getSpeedDialContactTypeList() {
      return instance.getSpeedDialContactTypeList();
    }
    /**
     * <code>repeated .com.fissy.dialer.callintent.SpeedDialContactType.Type speed_dial_contact_type = 4;</code>
     */
    public int getSpeedDialContactTypeCount() {
      return instance.getSpeedDialContactTypeCount();
    }
    /**
     * <code>repeated .com.fissy.dialer.callintent.SpeedDialContactType.Type speed_dial_contact_type = 4;</code>
     */
    public com.fissy.dialer.callintent.SpeedDialContactType.Type getSpeedDialContactType(int index) {
      return instance.getSpeedDialContactType(index);
    }
    /**
     * <code>repeated .com.fissy.dialer.callintent.SpeedDialContactType.Type speed_dial_contact_type = 4;</code>
     */
    public Builder setSpeedDialContactType(
        int index, com.fissy.dialer.callintent.SpeedDialContactType.Type value) {
      copyOnWrite();
      instance.setSpeedDialContactType(index, value);
      return this;
    }
    /**
     * <code>repeated .com.fissy.dialer.callintent.SpeedDialContactType.Type speed_dial_contact_type = 4;</code>
     */
    public Builder addSpeedDialContactType(com.fissy.dialer.callintent.SpeedDialContactType.Type value) {
      copyOnWrite();
      instance.addSpeedDialContactType(value);
      return this;
    }
    /**
     * <code>repeated .com.fissy.dialer.callintent.SpeedDialContactType.Type speed_dial_contact_type = 4;</code>
     */
    public Builder addAllSpeedDialContactType(
        java.lang.Iterable<? extends com.fissy.dialer.callintent.SpeedDialContactType.Type> values) {
      copyOnWrite();
      instance.addAllSpeedDialContactType(values);  return this;
    }
    /**
     * <code>repeated .com.fissy.dialer.callintent.SpeedDialContactType.Type speed_dial_contact_type = 4;</code>
     */
    public Builder clearSpeedDialContactType() {
      copyOnWrite();
      instance.clearSpeedDialContactType();
      return this;
    }

    /**
     * <code>optional int32 speed_dial_contact_position = 5;</code>
     */
    public boolean hasSpeedDialContactPosition() {
      return instance.hasSpeedDialContactPosition();
    }
    /**
     * <code>optional int32 speed_dial_contact_position = 5;</code>
     */
    public int getSpeedDialContactPosition() {
      return instance.getSpeedDialContactPosition();
    }
    /**
     * <code>optional int32 speed_dial_contact_position = 5;</code>
     */
    public Builder setSpeedDialContactPosition(int value) {
      copyOnWrite();
      instance.setSpeedDialContactPosition(value);
      return this;
    }
    /**
     * <code>optional int32 speed_dial_contact_position = 5;</code>
     */
    public Builder clearSpeedDialContactPosition() {
      copyOnWrite();
      instance.clearSpeedDialContactPosition();
      return this;
    }

    /**
     * <code>optional int64 time_since_app_launch = 6;</code>
     */
    public boolean hasTimeSinceAppLaunch() {
      return instance.hasTimeSinceAppLaunch();
    }
    /**
     * <code>optional int64 time_since_app_launch = 6;</code>
     */
    public long getTimeSinceAppLaunch() {
      return instance.getTimeSinceAppLaunch();
    }
    /**
     * <code>optional int64 time_since_app_launch = 6;</code>
     */
    public Builder setTimeSinceAppLaunch(long value) {
      copyOnWrite();
      instance.setTimeSinceAppLaunch(value);
      return this;
    }
    /**
     * <code>optional int64 time_since_app_launch = 6;</code>
     */
    public Builder clearTimeSinceAppLaunch() {
      copyOnWrite();
      instance.clearTimeSinceAppLaunch();
      return this;
    }

    /**
     * <code>optional int64 time_since_first_click = 7;</code>
     */
    public boolean hasTimeSinceFirstClick() {
      return instance.hasTimeSinceFirstClick();
    }
    /**
     * <code>optional int64 time_since_first_click = 7;</code>
     */
    public long getTimeSinceFirstClick() {
      return instance.getTimeSinceFirstClick();
    }
    /**
     * <code>optional int64 time_since_first_click = 7;</code>
     */
    public Builder setTimeSinceFirstClick(long value) {
      copyOnWrite();
      instance.setTimeSinceFirstClick(value);
      return this;
    }
    /**
     * <code>optional int64 time_since_first_click = 7;</code>
     */
    public Builder clearTimeSinceFirstClick() {
      copyOnWrite();
      instance.clearTimeSinceFirstClick();
      return this;
    }

    /**
     * <pre>
     * The following two list should be of the same length
     * (adding another message is not allowed here)
     * </pre>
     *
     * <code>repeated .com.fissy.dialer.logging.UiAction.Type ui_actions_since_app_launch = 8;</code>
     */
    public java.util.List<com.fissy.dialer.logging.UiAction.Type> getUiActionsSinceAppLaunchList() {
      return instance.getUiActionsSinceAppLaunchList();
    }
    /**
     * <pre>
     * The following two list should be of the same length
     * (adding another message is not allowed here)
     * </pre>
     *
     * <code>repeated .com.fissy.dialer.logging.UiAction.Type ui_actions_since_app_launch = 8;</code>
     */
    public int getUiActionsSinceAppLaunchCount() {
      return instance.getUiActionsSinceAppLaunchCount();
    }
    /**
     * <pre>
     * The following two list should be of the same length
     * (adding another message is not allowed here)
     * </pre>
     *
     * <code>repeated .com.fissy.dialer.logging.UiAction.Type ui_actions_since_app_launch = 8;</code>
     */
    public com.fissy.dialer.logging.UiAction.Type getUiActionsSinceAppLaunch(int index) {
      return instance.getUiActionsSinceAppLaunch(index);
    }
    /**
     * <pre>
     * The following two list should be of the same length
     * (adding another message is not allowed here)
     * </pre>
     *
     * <code>repeated .com.fissy.dialer.logging.UiAction.Type ui_actions_since_app_launch = 8;</code>
     */
    public Builder setUiActionsSinceAppLaunch(
        int index, com.fissy.dialer.logging.UiAction.Type value) {
      copyOnWrite();
      instance.setUiActionsSinceAppLaunch(index, value);
      return this;
    }
    /**
     * <pre>
     * The following two list should be of the same length
     * (adding another message is not allowed here)
     * </pre>
     *
     * <code>repeated .com.fissy.dialer.logging.UiAction.Type ui_actions_since_app_launch = 8;</code>
     */
    public Builder addUiActionsSinceAppLaunch(com.fissy.dialer.logging.UiAction.Type value) {
      copyOnWrite();
      instance.addUiActionsSinceAppLaunch(value);
      return this;
    }
    /**
     * <pre>
     * The following two list should be of the same length
     * (adding another message is not allowed here)
     * </pre>
     *
     * <code>repeated .com.fissy.dialer.logging.UiAction.Type ui_actions_since_app_launch = 8;</code>
     */
    public Builder addAllUiActionsSinceAppLaunch(
        java.lang.Iterable<? extends com.fissy.dialer.logging.UiAction.Type> values) {
      copyOnWrite();
      instance.addAllUiActionsSinceAppLaunch(values);  return this;
    }
    /**
     * <pre>
     * The following two list should be of the same length
     * (adding another message is not allowed here)
     * </pre>
     *
     * <code>repeated .com.fissy.dialer.logging.UiAction.Type ui_actions_since_app_launch = 8;</code>
     */
    public Builder clearUiActionsSinceAppLaunch() {
      copyOnWrite();
      instance.clearUiActionsSinceAppLaunch();
      return this;
    }

    /**
     * <code>repeated int64 ui_action_timestamps_since_app_launch = 9;</code>
     */
    public java.util.List<java.lang.Long>
        getUiActionTimestampsSinceAppLaunchList() {
      return java.util.Collections.unmodifiableList(
          instance.getUiActionTimestampsSinceAppLaunchList());
    }
    /**
     * <code>repeated int64 ui_action_timestamps_since_app_launch = 9;</code>
     */
    public int getUiActionTimestampsSinceAppLaunchCount() {
      return instance.getUiActionTimestampsSinceAppLaunchCount();
    }
    /**
     * <code>repeated int64 ui_action_timestamps_since_app_launch = 9;</code>
     */
    public long getUiActionTimestampsSinceAppLaunch(int index) {
      return instance.getUiActionTimestampsSinceAppLaunch(index);
    }
    /**
     * <code>repeated int64 ui_action_timestamps_since_app_launch = 9;</code>
     */
    public Builder setUiActionTimestampsSinceAppLaunch(
        int index, long value) {
      copyOnWrite();
      instance.setUiActionTimestampsSinceAppLaunch(index, value);
      return this;
    }
    /**
     * <code>repeated int64 ui_action_timestamps_since_app_launch = 9;</code>
     */
    public Builder addUiActionTimestampsSinceAppLaunch(long value) {
      copyOnWrite();
      instance.addUiActionTimestampsSinceAppLaunch(value);
      return this;
    }
    /**
     * <code>repeated int64 ui_action_timestamps_since_app_launch = 9;</code>
     */
    public Builder addAllUiActionTimestampsSinceAppLaunch(
        java.lang.Iterable<? extends java.lang.Long> values) {
      copyOnWrite();
      instance.addAllUiActionTimestampsSinceAppLaunch(values);
      return this;
    }
    /**
     * <code>repeated int64 ui_action_timestamps_since_app_launch = 9;</code>
     */
    public Builder clearUiActionTimestampsSinceAppLaunch() {
      copyOnWrite();
      instance.clearUiActionTimestampsSinceAppLaunch();
      return this;
    }

    /**
     * <code>optional int32 starting_tab_index = 10;</code>
     */
    public boolean hasStartingTabIndex() {
      return instance.hasStartingTabIndex();
    }
    /**
     * <code>optional int32 starting_tab_index = 10;</code>
     */
    public int getStartingTabIndex() {
      return instance.getStartingTabIndex();
    }
    /**
     * <code>optional int32 starting_tab_index = 10;</code>
     */
    public Builder setStartingTabIndex(int value) {
      copyOnWrite();
      instance.setStartingTabIndex(value);
      return this;
    }
    /**
     * <code>optional int32 starting_tab_index = 10;</code>
     */
    public Builder clearStartingTabIndex() {
      copyOnWrite();
      instance.clearStartingTabIndex();
      return this;
    }

    /**
     * <pre>
     * For recording the appearance of video call button
     * </pre>
     *
     * <code>optional int32 lightbringer_button_appear_in_expanded_call_log_item_count = 11;</code>
     */
    public boolean hasLightbringerButtonAppearInExpandedCallLogItemCount() {
      return instance.hasLightbringerButtonAppearInExpandedCallLogItemCount();
    }
    /**
     * <pre>
     * For recording the appearance of video call button
     * </pre>
     *
     * <code>optional int32 lightbringer_button_appear_in_expanded_call_log_item_count = 11;</code>
     */
    public int getLightbringerButtonAppearInExpandedCallLogItemCount() {
      return instance.getLightbringerButtonAppearInExpandedCallLogItemCount();
    }
    /**
     * <pre>
     * For recording the appearance of video call button
     * </pre>
     *
     * <code>optional int32 lightbringer_button_appear_in_expanded_call_log_item_count = 11;</code>
     */
    public Builder setLightbringerButtonAppearInExpandedCallLogItemCount(int value) {
      copyOnWrite();
      instance.setLightbringerButtonAppearInExpandedCallLogItemCount(value);
      return this;
    }
    /**
     * <pre>
     * For recording the appearance of video call button
     * </pre>
     *
     * <code>optional int32 lightbringer_button_appear_in_expanded_call_log_item_count = 11;</code>
     */
    public Builder clearLightbringerButtonAppearInExpandedCallLogItemCount() {
      copyOnWrite();
      instance.clearLightbringerButtonAppearInExpandedCallLogItemCount();
      return this;
    }

    /**
     * <code>optional int32 lightbringer_button_appear_in_collapsed_call_log_item_count = 12;</code>
     */
    public boolean hasLightbringerButtonAppearInCollapsedCallLogItemCount() {
      return instance.hasLightbringerButtonAppearInCollapsedCallLogItemCount();
    }
    /**
     * <code>optional int32 lightbringer_button_appear_in_collapsed_call_log_item_count = 12;</code>
     */
    public int getLightbringerButtonAppearInCollapsedCallLogItemCount() {
      return instance.getLightbringerButtonAppearInCollapsedCallLogItemCount();
    }
    /**
     * <code>optional int32 lightbringer_button_appear_in_collapsed_call_log_item_count = 12;</code>
     */
    public Builder setLightbringerButtonAppearInCollapsedCallLogItemCount(int value) {
      copyOnWrite();
      instance.setLightbringerButtonAppearInCollapsedCallLogItemCount(value);
      return this;
    }
    /**
     * <code>optional int32 lightbringer_button_appear_in_collapsed_call_log_item_count = 12;</code>
     */
    public Builder clearLightbringerButtonAppearInCollapsedCallLogItemCount() {
      copyOnWrite();
      instance.clearLightbringerButtonAppearInCollapsedCallLogItemCount();
      return this;
    }

    /**
     * <code>optional int32 lightbringer_button_appear_in_search_count = 13;</code>
     */
    public boolean hasLightbringerButtonAppearInSearchCount() {
      return instance.hasLightbringerButtonAppearInSearchCount();
    }
    /**
     * <code>optional int32 lightbringer_button_appear_in_search_count = 13;</code>
     */
    public int getLightbringerButtonAppearInSearchCount() {
      return instance.getLightbringerButtonAppearInSearchCount();
    }
    /**
     * <code>optional int32 lightbringer_button_appear_in_search_count = 13;</code>
     */
    public Builder setLightbringerButtonAppearInSearchCount(int value) {
      copyOnWrite();
      instance.setLightbringerButtonAppearInSearchCount(value);
      return this;
    }
    /**
     * <code>optional int32 lightbringer_button_appear_in_search_count = 13;</code>
     */
    public Builder clearLightbringerButtonAppearInSearchCount() {
      copyOnWrite();
      instance.clearLightbringerButtonAppearInSearchCount();
      return this;
    }

    /**
     * <pre>
     * Indicates that the call is open to modification from assisted dialing.
     * </pre>
     *
     * <code>optional bool allow_assisted_dialing = 14;</code>
     */
    public boolean hasAllowAssistedDialing() {
      return instance.hasAllowAssistedDialing();
    }
    /**
     * <pre>
     * Indicates that the call is open to modification from assisted dialing.
     * </pre>
     *
     * <code>optional bool allow_assisted_dialing = 14;</code>
     */
    public boolean getAllowAssistedDialing() {
      return instance.getAllowAssistedDialing();
    }
    /**
     * <pre>
     * Indicates that the call is open to modification from assisted dialing.
     * </pre>
     *
     * <code>optional bool allow_assisted_dialing = 14;</code>
     */
    public Builder setAllowAssistedDialing(boolean value) {
      copyOnWrite();
      instance.setAllowAssistedDialing(value);
      return this;
    }
    /**
     * <pre>
     * Indicates that the call is open to modification from assisted dialing.
     * </pre>
     *
     * <code>optional bool allow_assisted_dialing = 14;</code>
     */
    public Builder clearAllowAssistedDialing() {
      copyOnWrite();
      instance.clearAllowAssistedDialing();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.fissy.dialer.callintent.CallSpecificAppData)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.fissy.dialer.callintent.CallSpecificAppData();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        speedDialContactType_.makeImmutable();
        uiActionsSinceAppLaunch_.makeImmutable();
        uiActionTimestampsSinceAppLaunch_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.fissy.dialer.callintent.CallSpecificAppData other = (com.fissy.dialer.callintent.CallSpecificAppData) arg1;
        callInitiationType_ = visitor.visitInt(hasCallInitiationType(), callInitiationType_,
            other.hasCallInitiationType(), other.callInitiationType_);
        positionOfSelectedSearchResult_ = visitor.visitInt(
            hasPositionOfSelectedSearchResult(), positionOfSelectedSearchResult_,
            other.hasPositionOfSelectedSearchResult(), other.positionOfSelectedSearchResult_);
        charactersInSearchString_ = visitor.visitInt(
            hasCharactersInSearchString(), charactersInSearchString_,
            other.hasCharactersInSearchString(), other.charactersInSearchString_);
        speedDialContactType_= visitor.visitIntList(speedDialContactType_, other.speedDialContactType_);
        speedDialContactPosition_ = visitor.visitInt(
            hasSpeedDialContactPosition(), speedDialContactPosition_,
            other.hasSpeedDialContactPosition(), other.speedDialContactPosition_);
        timeSinceAppLaunch_ = visitor.visitLong(
            hasTimeSinceAppLaunch(), timeSinceAppLaunch_,
            other.hasTimeSinceAppLaunch(), other.timeSinceAppLaunch_);
        timeSinceFirstClick_ = visitor.visitLong(
            hasTimeSinceFirstClick(), timeSinceFirstClick_,
            other.hasTimeSinceFirstClick(), other.timeSinceFirstClick_);
        uiActionsSinceAppLaunch_= visitor.visitIntList(uiActionsSinceAppLaunch_, other.uiActionsSinceAppLaunch_);
        uiActionTimestampsSinceAppLaunch_= visitor.visitLongList(uiActionTimestampsSinceAppLaunch_, other.uiActionTimestampsSinceAppLaunch_);
        startingTabIndex_ = visitor.visitInt(
            hasStartingTabIndex(), startingTabIndex_,
            other.hasStartingTabIndex(), other.startingTabIndex_);
        lightbringerButtonAppearInExpandedCallLogItemCount_ = visitor.visitInt(
            hasLightbringerButtonAppearInExpandedCallLogItemCount(), lightbringerButtonAppearInExpandedCallLogItemCount_,
            other.hasLightbringerButtonAppearInExpandedCallLogItemCount(), other.lightbringerButtonAppearInExpandedCallLogItemCount_);
        lightbringerButtonAppearInCollapsedCallLogItemCount_ = visitor.visitInt(
            hasLightbringerButtonAppearInCollapsedCallLogItemCount(), lightbringerButtonAppearInCollapsedCallLogItemCount_,
            other.hasLightbringerButtonAppearInCollapsedCallLogItemCount(), other.lightbringerButtonAppearInCollapsedCallLogItemCount_);
        lightbringerButtonAppearInSearchCount_ = visitor.visitInt(
            hasLightbringerButtonAppearInSearchCount(), lightbringerButtonAppearInSearchCount_,
            other.hasLightbringerButtonAppearInSearchCount(), other.lightbringerButtonAppearInSearchCount_);
        allowAssistedDialing_ = visitor.visitBoolean(
            hasAllowAssistedDialing(), allowAssistedDialing_,
            other.hasAllowAssistedDialing(), other.allowAssistedDialing_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                com.fissy.dialer.callintent.CallInitiationType.Type value = com.fissy.dialer.callintent.CallInitiationType.Type.forNumber(rawValue);
                if (value == null) {
                  super.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  callInitiationType_ = rawValue;
                }
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                positionOfSelectedSearchResult_ = input.readInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                charactersInSearchString_ = input.readInt32();
                break;
              }
              case 32: {
                if (!speedDialContactType_.isModifiable()) {
                  speedDialContactType_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(speedDialContactType_);
                }
                int rawValue = input.readEnum();
                com.fissy.dialer.callintent.SpeedDialContactType.Type value = com.fissy.dialer.callintent.SpeedDialContactType.Type.forNumber(rawValue);
                if (value == null) {
                  super.mergeVarintField(4, rawValue);
                } else {
                  speedDialContactType_.addInt(rawValue);
                }
                break;
              }
              case 34: {
                if (!speedDialContactType_.isModifiable()) {
                  speedDialContactType_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(speedDialContactType_);
                }
                int length = input.readRawVarint32();
                int oldLimit = input.pushLimit(length);
                while(input.getBytesUntilLimit() > 0) {
                  int rawValue = input.readEnum();
                  com.fissy.dialer.callintent.SpeedDialContactType.Type value = com.fissy.dialer.callintent.SpeedDialContactType.Type.forNumber(rawValue);
                  if (value == null) {
                    super.mergeVarintField(4, rawValue);
                  } else {
                    speedDialContactType_.addInt(rawValue);
                  }
                }
                input.popLimit(oldLimit);
                break;
              }
              case 40: {
                bitField0_ |= 0x00000008;
                speedDialContactPosition_ = input.readInt32();
                break;
              }
              case 48: {
                bitField0_ |= 0x00000010;
                timeSinceAppLaunch_ = input.readInt64();
                break;
              }
              case 56: {
                bitField0_ |= 0x00000020;
                timeSinceFirstClick_ = input.readInt64();
                break;
              }
              case 64: {
                if (!uiActionsSinceAppLaunch_.isModifiable()) {
                  uiActionsSinceAppLaunch_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(uiActionsSinceAppLaunch_);
                }
                int rawValue = input.readEnum();
                com.fissy.dialer.logging.UiAction.Type value = com.fissy.dialer.logging.UiAction.Type.forNumber(rawValue);
                if (value == null) {
                  super.mergeVarintField(8, rawValue);
                } else {
                  uiActionsSinceAppLaunch_.addInt(rawValue);
                }
                break;
              }
              case 66: {
                if (!uiActionsSinceAppLaunch_.isModifiable()) {
                  uiActionsSinceAppLaunch_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(uiActionsSinceAppLaunch_);
                }
                int length = input.readRawVarint32();
                int oldLimit = input.pushLimit(length);
                while(input.getBytesUntilLimit() > 0) {
                  int rawValue = input.readEnum();
                  com.fissy.dialer.logging.UiAction.Type value = com.fissy.dialer.logging.UiAction.Type.forNumber(rawValue);
                  if (value == null) {
                    super.mergeVarintField(8, rawValue);
                  } else {
                    uiActionsSinceAppLaunch_.addInt(rawValue);
                  }
                }
                input.popLimit(oldLimit);
                break;
              }
              case 72: {
                if (!uiActionTimestampsSinceAppLaunch_.isModifiable()) {
                  uiActionTimestampsSinceAppLaunch_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(uiActionTimestampsSinceAppLaunch_);
                }
                uiActionTimestampsSinceAppLaunch_.addLong(input.readInt64());
                break;
              }
              case 74: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!uiActionTimestampsSinceAppLaunch_.isModifiable() && input.getBytesUntilLimit() > 0) {
                  uiActionTimestampsSinceAppLaunch_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(uiActionTimestampsSinceAppLaunch_);
                }
                while (input.getBytesUntilLimit() > 0) {
                  uiActionTimestampsSinceAppLaunch_.addLong(input.readInt64());
                }
                input.popLimit(limit);
                break;
              }
              case 80: {
                bitField0_ |= 0x00000040;
                startingTabIndex_ = input.readInt32();
                break;
              }
              case 88: {
                bitField0_ |= 0x00000080;
                lightbringerButtonAppearInExpandedCallLogItemCount_ = input.readInt32();
                break;
              }
              case 96: {
                bitField0_ |= 0x00000100;
                lightbringerButtonAppearInCollapsedCallLogItemCount_ = input.readInt32();
                break;
              }
              case 104: {
                bitField0_ |= 0x00000200;
                lightbringerButtonAppearInSearchCount_ = input.readInt32();
                break;
              }
              case 112: {
                bitField0_ |= 0x00000400;
                allowAssistedDialing_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.fissy.dialer.callintent.CallSpecificAppData.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.fissy.dialer.callintent.CallSpecificAppData)
  private static final com.fissy.dialer.callintent.CallSpecificAppData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CallSpecificAppData();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.fissy.dialer.callintent.CallSpecificAppData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CallSpecificAppData> PARSER;

  public static com.google.protobuf.Parser<CallSpecificAppData> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

