// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/android/dialer/voicemail/model/voicemail_entry.proto

package com.fissy.dialer.voicemail.model;

public interface VoicemailEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fissy.dialer.voicemail.model.VoicemailEntry)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Value in column AnnotatedCallLog._ID
   * </pre>
   *
   * <code>optional int64 id = 1;</code>
   */
  boolean hasId();
  /**
   * <pre>
   * Value in column AnnotatedCallLog._ID
   * </pre>
   *
   * <code>optional int64 id = 1;</code>
   */
  long getId();

  /**
   * <pre>
   * Value in column AnnotatedCallLog.TIMESTAMP
   * </pre>
   *
   * <code>optional int64 timestamp = 2;</code>
   */
  boolean hasTimestamp();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.TIMESTAMP
   * </pre>
   *
   * <code>optional int64 timestamp = 2;</code>
   */
  long getTimestamp();

  /**
   * <pre>
   * Value in column AnnotatedCallLog.NUMBER
   * </pre>
   *
   * <code>optional .com.fissy.dialer.DialerPhoneNumber number = 3;</code>
   */
  boolean hasNumber();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.NUMBER
   * </pre>
   *
   * <code>optional .com.fissy.dialer.DialerPhoneNumber number = 3;</code>
   */
  com.fissy.dialer.DialerPhoneNumber getNumber();

  /**
   * <pre>
   * Value in column AnnotatedCallLog.FORMATTED_NUMBER
   * </pre>
   *
   * <code>optional string formatted_number = 4;</code>
   */
  boolean hasFormattedNumber();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.FORMATTED_NUMBER
   * </pre>
   *
   * <code>optional string formatted_number = 4;</code>
   */
  java.lang.String getFormattedNumber();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.FORMATTED_NUMBER
   * </pre>
   *
   * <code>optional string formatted_number = 4;</code>
   */
  com.google.protobuf.ByteString
      getFormattedNumberBytes();

  /**
   * <pre>
   * Value in column AnnotatedCallLog.GEOCODED_LOCATION
   * </pre>
   *
   * <code>optional string geocoded_location = 5;</code>
   */
  boolean hasGeocodedLocation();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.GEOCODED_LOCATION
   * </pre>
   *
   * <code>optional string geocoded_location = 5;</code>
   */
  java.lang.String getGeocodedLocation();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.GEOCODED_LOCATION
   * </pre>
   *
   * <code>optional string geocoded_location = 5;</code>
   */
  com.google.protobuf.ByteString
      getGeocodedLocationBytes();

  /**
   * <pre>
   * Value in column AnnotatedCallLog.DURATION
   * </pre>
   *
   * <code>optional int64 duration = 6;</code>
   */
  boolean hasDuration();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.DURATION
   * </pre>
   *
   * <code>optional int64 duration = 6;</code>
   */
  long getDuration();

  /**
   * <pre>
   * Value in column AnnotatedCallLog.TRANSCRIPTION
   * </pre>
   *
   * <code>optional string transcription = 7;</code>
   */
  boolean hasTranscription();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.TRANSCRIPTION
   * </pre>
   *
   * <code>optional string transcription = 7;</code>
   */
  java.lang.String getTranscription();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.TRANSCRIPTION
   * </pre>
   *
   * <code>optional string transcription = 7;</code>
   */
  com.google.protobuf.ByteString
      getTranscriptionBytes();

  /**
   * <pre>
   * Value in column AnnotatedCallLog.VOICEMAIL_URI
   * </pre>
   *
   * <code>optional string voicemail_uri = 8;</code>
   */
  boolean hasVoicemailUri();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.VOICEMAIL_URI
   * </pre>
   *
   * <code>optional string voicemail_uri = 8;</code>
   */
  java.lang.String getVoicemailUri();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.VOICEMAIL_URI
   * </pre>
   *
   * <code>optional string voicemail_uri = 8;</code>
   */
  com.google.protobuf.ByteString
      getVoicemailUriBytes();

  /**
   * <pre>
   * Value in column AnnotatedCallLog.CALL_TYPE
   * </pre>
   *
   * <code>optional int32 call_type = 9;</code>
   */
  boolean hasCallType();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.CALL_TYPE
   * </pre>
   *
   * <code>optional int32 call_type = 9;</code>
   */
  int getCallType();

  /**
   * <pre>
   * Value in column AnnotatedCallLog.IS_READ
   * </pre>
   *
   * <code>optional int32 is_read = 10;</code>
   */
  boolean hasIsRead();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.IS_READ
   * </pre>
   *
   * <code>optional int32 is_read = 10;</code>
   */
  int getIsRead();

  /**
   * <pre>
   * Value in column AnnotatedCallLog.NUMBER_ATTRIBUTES
   * </pre>
   *
   * <code>optional .com.fissy.dialer.NumberAttributes number_attributes = 11;</code>
   */
  boolean hasNumberAttributes();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.NUMBER_ATTRIBUTES
   * </pre>
   *
   * <code>optional .com.fissy.dialer.NumberAttributes number_attributes = 11;</code>
   */
  com.fissy.dialer.NumberAttributes getNumberAttributes();

  /**
   * <pre>
   * Value in column AnnotatedCallLog.TRANSCRIPTION_STATE
   * </pre>
   *
   * <code>optional int32 transcription_state = 12;</code>
   */
  boolean hasTranscriptionState();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.TRANSCRIPTION_STATE
   * </pre>
   *
   * <code>optional int32 transcription_state = 12;</code>
   */
  int getTranscriptionState();

  /**
   * <pre>
   * Value in column AnnotatedCallLog.PHONE_ACCOUNT_COMPONENT_NAME
   * </pre>
   *
   * <code>optional string phone_account_component_name = 13;</code>
   */
  boolean hasPhoneAccountComponentName();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.PHONE_ACCOUNT_COMPONENT_NAME
   * </pre>
   *
   * <code>optional string phone_account_component_name = 13;</code>
   */
  java.lang.String getPhoneAccountComponentName();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.PHONE_ACCOUNT_COMPONENT_NAME
   * </pre>
   *
   * <code>optional string phone_account_component_name = 13;</code>
   */
  com.google.protobuf.ByteString
      getPhoneAccountComponentNameBytes();

  /**
   * <pre>
   * Value in column AnnotatedCallLog.PHONE_ACCOUNT_ID
   * </pre>
   *
   * <code>optional string phone_account_id = 14;</code>
   */
  boolean hasPhoneAccountId();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.PHONE_ACCOUNT_ID
   * </pre>
   *
   * <code>optional string phone_account_id = 14;</code>
   */
  java.lang.String getPhoneAccountId();
  /**
   * <pre>
   * Value in column AnnotatedCallLog.PHONE_ACCOUNT_ID
   * </pre>
   *
   * <code>optional string phone_account_id = 14;</code>
   */
  com.google.protobuf.ByteString
      getPhoneAccountIdBytes();
}
