// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/android/dialer/calldetails/proto/call_details_entries.proto

package com.fissy.dialer.calldetails;

public final class CallDetailsEntriesOuterClass {
  private CallDetailsEntriesOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
