// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/fissy/dialer/phonelookup/phone_lookup_info.proto

package com.fissy.dialer.phonelookup;

public final class PhoneLookupInfoOuterClass {

    private PhoneLookupInfoOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
