// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/android/voicemail/impl/transcribe/grpc/voicemail_transcription.proto

package com.google.internal.communications.voicemailtranscription.v1;

/**
 * <pre>
 * Request for uploading transcription ratings.
 * </pre>
 *
 * Protobuf type {@code google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest}
 */
public  final class SendTranscriptionFeedbackRequest extends
    com.google.protobuf.GeneratedMessageLite<
        SendTranscriptionFeedbackRequest, SendTranscriptionFeedbackRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest)
    SendTranscriptionFeedbackRequestOrBuilder {
  private SendTranscriptionFeedbackRequest() {
    rating_ = emptyProtobufList();
  }
  public static final int RATING_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating> rating_;
  /**
   * <pre>
   * User feedback indicating the transcription quality for one or more
   * voicemails
   * </pre>
   *
   * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
   */
  public java.util.List<com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating> getRatingList() {
    return rating_;
  }
  /**
   * <pre>
   * User feedback indicating the transcription quality for one or more
   * voicemails
   * </pre>
   *
   * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
   */
  public java.util.List<? extends com.google.internal.communications.voicemailtranscription.v1.TranscriptionRatingOrBuilder> 
      getRatingOrBuilderList() {
    return rating_;
  }
  /**
   * <pre>
   * User feedback indicating the transcription quality for one or more
   * voicemails
   * </pre>
   *
   * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
   */
  public int getRatingCount() {
    return rating_.size();
  }
  /**
   * <pre>
   * User feedback indicating the transcription quality for one or more
   * voicemails
   * </pre>
   *
   * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
   */
  public com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating getRating(int index) {
    return rating_.get(index);
  }
  /**
   * <pre>
   * User feedback indicating the transcription quality for one or more
   * voicemails
   * </pre>
   *
   * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
   */
  public com.google.internal.communications.voicemailtranscription.v1.TranscriptionRatingOrBuilder getRatingOrBuilder(
      int index) {
    return rating_.get(index);
  }
  private void ensureRatingIsMutable() {
    if (!rating_.isModifiable()) {
      rating_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(rating_);
     }
  }

  /**
   * <pre>
   * User feedback indicating the transcription quality for one or more
   * voicemails
   * </pre>
   *
   * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
   */
  private void setRating(
      int index, com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureRatingIsMutable();
    rating_.set(index, value);
  }
  /**
   * <pre>
   * User feedback indicating the transcription quality for one or more
   * voicemails
   * </pre>
   *
   * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
   */
  private void setRating(
      int index, com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating.Builder builderForValue) {
    ensureRatingIsMutable();
    rating_.set(index, builderForValue.build());
  }
  /**
   * <pre>
   * User feedback indicating the transcription quality for one or more
   * voicemails
   * </pre>
   *
   * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
   */
  private void addRating(com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureRatingIsMutable();
    rating_.add(value);
  }
  /**
   * <pre>
   * User feedback indicating the transcription quality for one or more
   * voicemails
   * </pre>
   *
   * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
   */
  private void addRating(
      int index, com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureRatingIsMutable();
    rating_.add(index, value);
  }
  /**
   * <pre>
   * User feedback indicating the transcription quality for one or more
   * voicemails
   * </pre>
   *
   * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
   */
  private void addRating(
      com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating.Builder builderForValue) {
    ensureRatingIsMutable();
    rating_.add(builderForValue.build());
  }
  /**
   * <pre>
   * User feedback indicating the transcription quality for one or more
   * voicemails
   * </pre>
   *
   * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
   */
  private void addRating(
      int index, com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating.Builder builderForValue) {
    ensureRatingIsMutable();
    rating_.add(index, builderForValue.build());
  }
  /**
   * <pre>
   * User feedback indicating the transcription quality for one or more
   * voicemails
   * </pre>
   *
   * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
   */
  private void addAllRating(
      java.lang.Iterable<? extends com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating> values) {
    ensureRatingIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, rating_);
  }
  /**
   * <pre>
   * User feedback indicating the transcription quality for one or more
   * voicemails
   * </pre>
   *
   * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
   */
  private void clearRating() {
    rating_ = emptyProtobufList();
  }
  /**
   * <pre>
   * User feedback indicating the transcription quality for one or more
   * voicemails
   * </pre>
   *
   * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
   */
  private void removeRating(int index) {
    ensureRatingIsMutable();
    rating_.remove(index);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < rating_.size(); i++) {
      output.writeMessage(1, rating_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < rating_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, rating_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Request for uploading transcription ratings.
   * </pre>
   *
   * Protobuf type {@code google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest)
      com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequestOrBuilder {
    // Construct using com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * User feedback indicating the transcription quality for one or more
     * voicemails
     * </pre>
     *
     * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
     */
    public java.util.List<com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating> getRatingList() {
      return java.util.Collections.unmodifiableList(
          instance.getRatingList());
    }
    /**
     * <pre>
     * User feedback indicating the transcription quality for one or more
     * voicemails
     * </pre>
     *
     * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
     */
    public int getRatingCount() {
      return instance.getRatingCount();
    }/**
     * <pre>
     * User feedback indicating the transcription quality for one or more
     * voicemails
     * </pre>
     *
     * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
     */
    public com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating getRating(int index) {
      return instance.getRating(index);
    }
    /**
     * <pre>
     * User feedback indicating the transcription quality for one or more
     * voicemails
     * </pre>
     *
     * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
     */
    public Builder setRating(
        int index, com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating value) {
      copyOnWrite();
      instance.setRating(index, value);
      return this;
    }
    /**
     * <pre>
     * User feedback indicating the transcription quality for one or more
     * voicemails
     * </pre>
     *
     * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
     */
    public Builder setRating(
        int index, com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating.Builder builderForValue) {
      copyOnWrite();
      instance.setRating(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * User feedback indicating the transcription quality for one or more
     * voicemails
     * </pre>
     *
     * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
     */
    public Builder addRating(com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating value) {
      copyOnWrite();
      instance.addRating(value);
      return this;
    }
    /**
     * <pre>
     * User feedback indicating the transcription quality for one or more
     * voicemails
     * </pre>
     *
     * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
     */
    public Builder addRating(
        int index, com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating value) {
      copyOnWrite();
      instance.addRating(index, value);
      return this;
    }
    /**
     * <pre>
     * User feedback indicating the transcription quality for one or more
     * voicemails
     * </pre>
     *
     * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
     */
    public Builder addRating(
        com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating.Builder builderForValue) {
      copyOnWrite();
      instance.addRating(builderForValue);
      return this;
    }
    /**
     * <pre>
     * User feedback indicating the transcription quality for one or more
     * voicemails
     * </pre>
     *
     * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
     */
    public Builder addRating(
        int index, com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating.Builder builderForValue) {
      copyOnWrite();
      instance.addRating(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * User feedback indicating the transcription quality for one or more
     * voicemails
     * </pre>
     *
     * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
     */
    public Builder addAllRating(
        java.lang.Iterable<? extends com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating> values) {
      copyOnWrite();
      instance.addAllRating(values);
      return this;
    }
    /**
     * <pre>
     * User feedback indicating the transcription quality for one or more
     * voicemails
     * </pre>
     *
     * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
     */
    public Builder clearRating() {
      copyOnWrite();
      instance.clearRating();
      return this;
    }
    /**
     * <pre>
     * User feedback indicating the transcription quality for one or more
     * voicemails
     * </pre>
     *
     * <code>repeated .google.internal.communications.voicemailtranscription.v1.TranscriptionRating rating = 1;</code>
     */
    public Builder removeRating(int index) {
      copyOnWrite();
      instance.removeRating(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        rating_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest other = (com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest) arg1;
        rating_= visitor.visitList(rating_, other.rating_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                if (!rating_.isModifiable()) {
                  rating_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(rating_);
                }
                rating_.add(
                    input.readMessage(com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating.parser(), extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest)
  private static final com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SendTranscriptionFeedbackRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SendTranscriptionFeedbackRequest> PARSER;

  public static com.google.protobuf.Parser<SendTranscriptionFeedbackRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

