// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/android/voicemail/impl/transcribe/grpc/voicemail_transcription.proto

package com.google.internal.communications.voicemailtranscription.v1;

public interface SendTranscriptionFeedbackResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.internal.communications.voicemailtranscription.v1.SendTranscriptionFeedbackResponse)
    com.google.protobuf.MessageLiteOrBuilder {
}
