// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/android/voicemail/impl/transcribe/grpc/voicemail_transcription.proto

package com.google.internal.communications.voicemailtranscription.v1;

/**
 * <pre>
 * The rating for a single voicemail transcription.
 * </pre>
 *
 * Protobuf type {@code google.internal.communications.voicemailtranscription.v1.TranscriptionRating}
 */
public  final class TranscriptionRating extends
    com.google.protobuf.GeneratedMessageLite<
        TranscriptionRating, TranscriptionRating.Builder> implements
    // @@protoc_insertion_point(message_implements:google.internal.communications.voicemailtranscription.v1.TranscriptionRating)
    TranscriptionRatingOrBuilder {
  private TranscriptionRating() {
    transcriptionId_ = "";
    ratingValue_ = 0;
  }
  private int bitField0_;
  public static final int TRANSCRIPTION_ID_FIELD_NUMBER = 1;
  private java.lang.String transcriptionId_;
  /**
   * <pre>
   * The id of the voicemail transcription.
   * </pre>
   *
   * <code>optional string transcription_id = 1;</code>
   */
  public boolean hasTranscriptionId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * The id of the voicemail transcription.
   * </pre>
   *
   * <code>optional string transcription_id = 1;</code>
   */
  public java.lang.String getTranscriptionId() {
    return transcriptionId_;
  }
  /**
   * <pre>
   * The id of the voicemail transcription.
   * </pre>
   *
   * <code>optional string transcription_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTranscriptionIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(transcriptionId_);
  }
  /**
   * <pre>
   * The id of the voicemail transcription.
   * </pre>
   *
   * <code>optional string transcription_id = 1;</code>
   */
  private void setTranscriptionId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    transcriptionId_ = value;
  }
  /**
   * <pre>
   * The id of the voicemail transcription.
   * </pre>
   *
   * <code>optional string transcription_id = 1;</code>
   */
  private void clearTranscriptionId() {
    bitField0_ = (bitField0_ & ~0x00000001);
    transcriptionId_ = getDefaultInstance().getTranscriptionId();
  }
  /**
   * <pre>
   * The id of the voicemail transcription.
   * </pre>
   *
   * <code>optional string transcription_id = 1;</code>
   */
  private void setTranscriptionIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    transcriptionId_ = value.toStringUtf8();
  }

  public static final int RATING_VALUE_FIELD_NUMBER = 2;
  private int ratingValue_;
  /**
   * <pre>
   * The user's rating of the voicemail transcription.
   * </pre>
   *
   * <code>optional .google.internal.communications.voicemailtranscription.v1.TranscriptionRatingValue rating_value = 2;</code>
   */
  public boolean hasRatingValue() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   * The user's rating of the voicemail transcription.
   * </pre>
   *
   * <code>optional .google.internal.communications.voicemailtranscription.v1.TranscriptionRatingValue rating_value = 2;</code>
   */
  public com.google.internal.communications.voicemailtranscription.v1.TranscriptionRatingValue getRatingValue() {
    com.google.internal.communications.voicemailtranscription.v1.TranscriptionRatingValue result = com.google.internal.communications.voicemailtranscription.v1.TranscriptionRatingValue.forNumber(ratingValue_);
    return result == null ? com.google.internal.communications.voicemailtranscription.v1.TranscriptionRatingValue.TRANSCRIPTION_RATING_VALUE_UNSPECIFIED : result;
  }
  /**
   * <pre>
   * The user's rating of the voicemail transcription.
   * </pre>
   *
   * <code>optional .google.internal.communications.voicemailtranscription.v1.TranscriptionRatingValue rating_value = 2;</code>
   */
  private void setRatingValue(com.google.internal.communications.voicemailtranscription.v1.TranscriptionRatingValue value) {
    if (value == null) {
      throw new NullPointerException();
    }
    bitField0_ |= 0x00000002;
    ratingValue_ = value.getNumber();
  }
  /**
   * <pre>
   * The user's rating of the voicemail transcription.
   * </pre>
   *
   * <code>optional .google.internal.communications.voicemailtranscription.v1.TranscriptionRatingValue rating_value = 2;</code>
   */
  private void clearRatingValue() {
    bitField0_ = (bitField0_ & ~0x00000002);
    ratingValue_ = 0;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeString(1, getTranscriptionId());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeEnum(2, ratingValue_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getTranscriptionId());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, ratingValue_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * The rating for a single voicemail transcription.
   * </pre>
   *
   * Protobuf type {@code google.internal.communications.voicemailtranscription.v1.TranscriptionRating}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.internal.communications.voicemailtranscription.v1.TranscriptionRating)
      com.google.internal.communications.voicemailtranscription.v1.TranscriptionRatingOrBuilder {
    // Construct using com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The id of the voicemail transcription.
     * </pre>
     *
     * <code>optional string transcription_id = 1;</code>
     */
    public boolean hasTranscriptionId() {
      return instance.hasTranscriptionId();
    }
    /**
     * <pre>
     * The id of the voicemail transcription.
     * </pre>
     *
     * <code>optional string transcription_id = 1;</code>
     */
    public java.lang.String getTranscriptionId() {
      return instance.getTranscriptionId();
    }
    /**
     * <pre>
     * The id of the voicemail transcription.
     * </pre>
     *
     * <code>optional string transcription_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTranscriptionIdBytes() {
      return instance.getTranscriptionIdBytes();
    }
    /**
     * <pre>
     * The id of the voicemail transcription.
     * </pre>
     *
     * <code>optional string transcription_id = 1;</code>
     */
    public Builder setTranscriptionId(
        java.lang.String value) {
      copyOnWrite();
      instance.setTranscriptionId(value);
      return this;
    }
    /**
     * <pre>
     * The id of the voicemail transcription.
     * </pre>
     *
     * <code>optional string transcription_id = 1;</code>
     */
    public Builder clearTranscriptionId() {
      copyOnWrite();
      instance.clearTranscriptionId();
      return this;
    }
    /**
     * <pre>
     * The id of the voicemail transcription.
     * </pre>
     *
     * <code>optional string transcription_id = 1;</code>
     */
    public Builder setTranscriptionIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTranscriptionIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * The user's rating of the voicemail transcription.
     * </pre>
     *
     * <code>optional .google.internal.communications.voicemailtranscription.v1.TranscriptionRatingValue rating_value = 2;</code>
     */
    public boolean hasRatingValue() {
      return instance.hasRatingValue();
    }
    /**
     * <pre>
     * The user's rating of the voicemail transcription.
     * </pre>
     *
     * <code>optional .google.internal.communications.voicemailtranscription.v1.TranscriptionRatingValue rating_value = 2;</code>
     */
    public com.google.internal.communications.voicemailtranscription.v1.TranscriptionRatingValue getRatingValue() {
      return instance.getRatingValue();
    }
    /**
     * <pre>
     * The user's rating of the voicemail transcription.
     * </pre>
     *
     * <code>optional .google.internal.communications.voicemailtranscription.v1.TranscriptionRatingValue rating_value = 2;</code>
     */
    public Builder setRatingValue(com.google.internal.communications.voicemailtranscription.v1.TranscriptionRatingValue value) {
      copyOnWrite();
      instance.setRatingValue(value);
      return this;
    }
    /**
     * <pre>
     * The user's rating of the voicemail transcription.
     * </pre>
     *
     * <code>optional .google.internal.communications.voicemailtranscription.v1.TranscriptionRatingValue rating_value = 2;</code>
     */
    public Builder clearRatingValue() {
      copyOnWrite();
      instance.clearRatingValue();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.internal.communications.voicemailtranscription.v1.TranscriptionRating)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating other = (com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating) arg1;
        transcriptionId_ = visitor.visitString(
            hasTranscriptionId(), transcriptionId_,
            other.hasTranscriptionId(), other.transcriptionId_);
        ratingValue_ = visitor.visitInt(hasRatingValue(), ratingValue_,
            other.hasRatingValue(), other.ratingValue_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readString();
                bitField0_ |= 0x00000001;
                transcriptionId_ = s;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                com.google.internal.communications.voicemailtranscription.v1.TranscriptionRatingValue value = com.google.internal.communications.voicemailtranscription.v1.TranscriptionRatingValue.forNumber(rawValue);
                if (value == null) {
                  super.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  ratingValue_ = rawValue;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.internal.communications.voicemailtranscription.v1.TranscriptionRating)
  private static final com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TranscriptionRating();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.google.internal.communications.voicemailtranscription.v1.TranscriptionRating getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TranscriptionRating> PARSER;

  public static com.google.protobuf.Parser<TranscriptionRating> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

