// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/fissy/dialer/blockreportspam/block_report_spam_dialog_info.proto

package com.fissy.dialer.blockreportspam;

public final class BlockReportSpamDialogInfoOuterClass {
    static {
    }

    private BlockReportSpamDialogInfoOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
