// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/fissy/dialer/dialercontact/dialer_contact.proto

package com.fissy.dialer.dialercontact;

public interface SimDetailsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.fissy.dialer.dialercontact.SimDetails)
        com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Human readable netwrork name displayed to user where relevant
     * </pre>
     *
     * <code>optional string network = 1;</code>
     */
    boolean hasNetwork();

    /**
     * <pre>
     * Human readable netwrork name displayed to user where relevant
     * </pre>
     *
     * <code>optional string network = 1;</code>
     */
    java.lang.String getNetwork();

    /**
     * <pre>
     * Human readable netwrork name displayed to user where relevant
     * </pre>
     *
     * <code>optional string network = 1;</code>
     */
    com.google.protobuf.ByteString
    getNetworkBytes();

    /**
     * <pre>
     * This value represents a hex representation of a color (i.e. #ffffff)
     * </pre>
     *
     * <code>optional int32 color = 2;</code>
     */
    boolean hasColor();

    /**
     * <pre>
     * This value represents a hex representation of a color (i.e. #ffffff)
     * </pre>
     *
     * <code>optional int32 color = 2;</code>
     */
    int getColor();
}
